//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListSale
    {
        public int IdSale { get; set; }
        public System.DateTime datatime { get; set; }
        public int idTovara { get; set; }
        public int idClient { get; set; }
        public int Count { get; set; }
        public decimal Summa { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Sklad Sklad { get; set; }
    }
}
