//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sklad
    {
        public Sklad()
        {
            this.ListSales = new HashSet<ListSale>();
            this.Tovars = new HashSet<Tovar>();
            this.Korzinas = new HashSet<Korzina>();
        }
    
        public int idTovara { get; set; }
        public string nazvanie { get; set; }
        public int Count { get; set; }
    
        public virtual ICollection<ListSale> ListSales { get; set; }
        public virtual ICollection<Tovar> Tovars { get; set; }
        public virtual ICollection<Korzina> Korzinas { get; set; }
    }
}
