//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Korzina
    {
        public int IdKorz { get; set; }
        public Nullable<int> idTovara { get; set; }
        public string nazvT { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string opisanieT { get; set; }
        public Nullable<int> id { get; set; }
    
        public virtual Tovar Tovar { get; set; }
        public virtual Sklad Sklad { get; set; }
    }
}
