//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovar
    {
        public Tovar()
        {
            this.Korzinas = new HashSet<Korzina>();
        }
    
        public int idTovara { get; set; }
        public string proizvoditel { get; set; }
        public decimal price { get; set; }
        public string opisanie { get; set; }
        public int id { get; set; }
    
        public virtual Sklad Sklad { get; set; }
        public virtual ICollection<Korzina> Korzinas { get; set; }
    }
}
